### ISSUE TITLE
Add bookmarked class to lines as well

### ISSUE THREAD

**Issue by mjomble** [atom/bookmarks#33]
Currently the "bookmarked" CSS class is added to the line number element in the gutter, but it would be very helpful for customizing styles if the class was also added to the code line elements.

You could then change, for example, the background color of bookmarked lines with

```css
atom-text-editor::shadow .line.bookmarked {
  background-color: rgba(0, 153, 204, 0.3)
}
```

in your `styles.less` file.
